# Generated by Django 3.2.16 on 2022-11-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#DC143C', 'Crimson'), ('#DB7093', 'PaleVioletRed'), ('#FFA500', 'Orange'), ('#BDB76B', 'DarkKhaki'), ('#EE82EE', 'Violet'), ('#D2691E', 'Chocolate'), ('#C0C0C0', 'Silver'), ('#00FF00', 'Lime'), ('#00BFFF', 'DeepSkyBlue'), ('#808000', 'Olive')], max_length=7, verbose_name='Цвет'),
        ),
    ]
